language: node_js

node_js:
  - "10"

env:
  - CXX=g++-4.8 QTUM_RPC_ADDRESS='http://althash:pass@localhost:14889' SENDER_ADDRESS='hMZK8FNPRm54jvTLAGEs1biTCgyCkcsmna' WALLET_PASSPHRASE='pass'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

cache:
  directories:
    - "node_modules"

before_install:
  - wget https://github.com/HTMLCOIN/HTMLCOIN/releases/download/v2.5.0/htmlcoin-2.5.0-linux64.tar.gz

install:
  - tar -xvzf htmlcoin-2.5.0-linux64.tar.gz
  - npm install
  - mkdir test/data/.htmlcoin

script:
  - ./htmlcoin-2.5.0-linux64/bin/htmlcoind -testnet -logevents -rpcuser=althash -rpcpassword=pass -datadir=./test/data/.htmlcoin & 
  - sleep 10
  - npm run test:cleanenv

after_failure:
  - cat /home/machado/build/machado-rev/altweb3/test/data/.htmlcoin/testnet3/debug.log
